new 100m config files (used on Kisti)
ucgmsim/slurm_gm_workflow pull request #383
Opened 2021-06-29 00:21 UTC by jasonmotha

2021-06-29 01:23 UTC, jpa198 requested changes

2021-06-29 01:23 UTC, jpa198 commented on templates/gmsim/20.4.1.1/root_defaults.yaml
> +pSA_periods: [0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1, 0.12, 0.15, 0.17, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6, 7.5, 10.0]
Needs an im entry as per https://github.com/ucgmsim/slurm_gm_workflow/blob/master/templates/gmsim/20.4.1.2/root_defaults.yaml

2021-06-29 01:53 UTC, jpa198 commented on templates/gmsim/20.4.1.1/root_defaults.yaml
> +pSA_periods: [0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1, 0.12, 0.15, 0.17, 0.2, 0.25, 0.3, 0.4, 0.5, 0.6, 0.7, 0.75, 0.8, 0.9, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0, 6, 7.5, 10.0]
This line is now deprecated

2021-06-29 03:43 UTC, jpa198 approved these changes
Sure, looks ok
I do want to have an audit of the emod3d files at some point though. I know there a few that don't get used.

2021-06-29 03:47 UTC, jasonmotha commented
The audit is a good idea. You are probably the person with the best idea of EMOD3D params.

2021-06-29 03:49 UTC, jpa198 commented
> The audit is a good idea. You are probably the person with the best idea of EMOD3D params.

Yeah, it should be a scoped ticket though, given how potentially breaking of a change it is. It would include set_runparams too, as that adds some junk too

2021-07-06 03:04 UTC, shot0829 approved these changes

2021-07-06 03:04 UTC, merged