Install qcore like the old docker did
ucgmsim/slurm_gm_workflow pull request #394
Opened 2021-08-06 01:51 UTC by jpa198

If we don't need qcore to be installed each time, then we can remove the clone line. 
It should be based on latest qcore though.

This is to counter a change made in #388 line 36 of the old jenkins file

#### Description

#### Dependencies

#### Checklist
- Have you updated the README (yes/no)?
- Have you updated the CHANGELOG (yes/no)?

2021-08-06 02:03 UTC, sungeunbae approved these changes
If I remember correctly, installing qcore was under /tmp/slurm_gm_worklow/qcore then linked to somewhere less obscure when mounted onto docker's file system. If it is directly installed in /home/jenkins/qcore, I am afraid it could interfere with other testing that depends on qcore if executed  at the same time.

2021-08-06 02:04 UTC, sungeunbae requested changes
I clicked a wrong button. Github on phone is fiddly!

2021-08-06 02:06 UTC, jpa198 commented
> If I remember correctly, installing qcore was under /tmp/slurm_gm_worklow/qcore then linked to somewhere less obscure when mounted onto docker's file system. If it is directly installed in /home/jenkins/qcore, I am afraid it could interfere with other testing that depends on qcore if executed at the same time.

That's a valid issue. So in theory we should make a virtual environment for each repo, so that we can do this sort of installation without side effects

2021-08-06 03:36 UTC, jasonmotha commented
Who's going to be working on isolating the test environments? I guess that was a great thing about docker.

2021-08-06 03:44 UTC, shot0829 commented
it will require going through all jenkin's file and add in creating virt_env line.
and wipe the virt_env if test passed.
might need a cron-job to clean-up the failed ones in a set period.

2021-08-06 03:56 UTC, jpa198 commented
> it will require going through all jenkin's file and add in creating virt_env line.
> and wipe the virt_env if test passed.
> might need a cron-job to clean-up the failed ones in a set period.

There's a post step, we should always be able to run clean up right? We just never cleaned up the qcore download, so they always stuck around between jobs

2021-08-06 04:04 UTC, sungeunbae commented
> it will require going through all jenkin's file and add in creating virt_env line.
> and wipe the virt_env if test passed.
> might need a cron-job to clean-up the failed ones in a set period.

dont think it needs a virtual env. Just install under /tmp/slurm_gm_workflow/somehash/qcore and add it to PYTHONPATH and remove whole directory after the test. can be easily done altering Jenkinsfile

2021-08-06 04:05 UTC, shot0829 commented
> > it will require going through all jenkin's file and add in creating virt_env line.
> > and wipe the virt_env if test passed.
> > might need a cron-job to clean-up the failed ones in a set period.
> 
> dont think it needs a virtual env. Just install under /tmp/slurm_gm_workflow/somehash/qcore and add it to PYTHONPATH and remove whole directory after the test. can be easily done altering Jenkinsfile

I agree, that is a lot more simpler, easy and fast to achieve.

2021-08-08 22:47 UTC, jpa198 commented
Turns out it was already using the local qcore download, everything is fine, no need for this PR

2021-08-08 22:47 UTC, closed without merging