Workflow Refactor Phase 2 Part 2
ucgmsim/slurm_gm_workflow pull request #443
Opened 2022-05-30 02:07 UTC by joelridden

#### Description
Collection Script

Test Data Outputs:
(Needed)
[meta_test_needed.csv](https://github.com/ucgmsim/slurm_gm_workflow/files/8794857/meta_test_needed.csv)
(Actual)
[meta_test_actual.csv](https://github.com/ucgmsim/slurm_gm_workflow/files/8794866/meta_test_actual.csv)

Example Run Output (Actual):
[meta_actual.csv](https://github.com/ucgmsim/slurm_gm_workflow/files/8794881/meta_actual.csv)

#### Dependencies

#### Checklist
- Have you updated the README (yes/no)?
- Have you updated the CHANGELOG (yes/no)?

2022-06-02 01:58 UTC, jasonmotha requested changes
A couple of things - my comments probably make more sense in chronological order. 

Happy to have a chat about any of these things - I think most of them should make sense (and not be too many changes)

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +    if ch_count_type == "Needed":
I reckon creating an enum rather than using strings.

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +        proc_type_name = (
Is this easier to patch globally rather than "hack" here?

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +        df = get_rel_info(df, name_tuple[0], root_dir, db, ch_count_type)
This function appears to do more than just getting the rel_info - might be worth breaking it into two functions.

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +METADATA_PROC_TYPES = ["EMOD3D", "VM_GEN", "VM_PERT", "HF", "BB", "IM_calc", "AdvIM"]
Use the enum values here, I reckon.

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +        os.path.join(f"{root_dir}/Runs/{fault_name}/{rel_name}", "sim_params.yaml"),
There should be helper functions for this in sim_structure.py

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +            df.loc[rel_name, f"{proc_type_name}_runtime"] += runtime / 60
Arguable to use constants here. But I think 60 / 3600 is pretty obvious

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +        df = get_rel_info(df, name_tuple[0], root_dir, db, ch_count_type)
I think it's better to create a series and return that - then overwrite the row with that series?

I think you can do one lined labelled series. :thinking:

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +            df.loc[rel_name, df_location] = f"{low}-{high}"
duplicated code outside of conditional?

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +    df.loc[rel_name, "BB_nt"] = params["sim_duration"] / params["dt"]
![image](https://user-images.githubusercontent.com/25143301/171530349-899d5819-5563-47c6-9891-75d281a0baf1.png)


Just to be confusing there are 3 dts - HF / BB as in the subsection and looks like emod has the global one.

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +    }
global?

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +    fault_name = rel_name.split("_")[0] if "REL" in rel_name else rel_name
sim_structure too

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +    db.close()
Should be using context managers?

Aside, it's probably better to move the sql to mgmtDB.py (it's called that or similar) and use the class.

I think that will probably solve my issue with the get_rel_info being a large function too.

2022-06-02 01:58 UTC, jasonmotha commented on workflow/automation/metadata/collect_metadata.py
> +    df.loc[rel_name, "BB_nt"] = params["sim_duration"] / params["dt"]
IM_calc uses BB DT

2022-06-07 03:29 UTC, jasonmotha approved these changes

2022-06-09 22:33 UTC, jpa198 approved these changes
A couple of things I'd liked touched up, but won't stop it going in

2022-06-09 22:33 UTC, jpa198 commented on workflow/automation/lib/MgmtDB.py
> +                        "SELECT last_modified from state WHERE run_name=? AND status == ? AND proc_type=?",
For consistency with the rest of the file you should only use a single =. From my brief google, SQL doesn't have a difference between = and ==

2022-06-10 03:58 UTC, jpa198 submitted a review, later dismissed
Nice

2022-06-12 22:05 UTC, jasonmotha commented
Just one thing about the parse args. Either chuck it into a separate function or convert the args object into single variables right after the parse_args call.

2022-06-12 22:53 UTC, jpa198 commented on workflow/automation/metadata/collect_metadata.py
> +    root_dir, ch_count_type, output_ffp = parse_args()
That's not how that works

2022-06-12 22:54 UTC, jpa198 commented
> Just one thing about the parse args. Either chuck it into a separate function or convert the args object into single variables right after the parse_args call.

I thought that was fine. Only about 4 args.X calls in the function?

2022-06-12 22:59 UTC, joelridden commented on workflow/automation/metadata/collect_metadata.py
> +    root_dir, ch_count_type, output_ffp = parse_args()
Yep, whoops

2022-06-12 23:59 UTC, jasonmotha approved these changes

2022-06-13 00:00 UTC, jpa198 approved these changes

2022-06-13 00:01 UTC, merged