Python3.9 envs
ucgmsim/slurm_gm_workflow pull request #474
Opened 2023-04-16 22:24 UTC by jpa198

#### Description

#### Dependencies

#### Checklist
- Have you updated the README (yes/no)?
- Have you updated the CHANGELOG (yes/no)?

2023-04-16 23:59 UTC, jpa198 commented
Wiki page with how to perform the upgrade here: https://wiki.canterbury.ac.nz/display/QuakeCore/April+%2723+environment+upgrade+process

2023-04-17 00:05 UTC, joelridden approved these changes

2023-04-17 02:01 UTC, sungeunbae commented
chmod +x to update_env_to_py39.sh or update the doc to start with "bash"

2023-04-17 02:30 UTC, sungeunbae approved these changes

2023-04-18 00:09 UTC, joelridden approved these changes
Only thought of maybe adding some comments to the edit_cfg script so it's known the format you are reading / writing. But I think it's simple enough to understand if you actually read the code.

2023-04-18 20:53 UTC, joelridden approved these changes

2023-04-18 22:00 UTC, joelridden approved these changes

2023-04-18 22:22 UTC, sungeunbae requested changes

2023-04-18 22:22 UTC, sungeunbae commented on workflow/environments/org/nesi/update_env_to_py39.sh
> +    python $myenv/workflow/environments/org/nesi/edit_cfg.py $myenv/virt_envs/python3_mahuika/pyvenv.cfg include-system-site-packages true
shouldn't this be $myenv/workflow/workflow/environments ?

2023-04-18 22:22 UTC, sungeunbae commented on workflow/environments/org/nesi/update_env_to_py39.sh
> +    python $myenv/workflow/environments/org/nesi/edit_cfg.py $myenv/virt_envs/python3_maui/pyvenv.cfg include-system-site-packages true
Same as above?

2023-04-18 22:52 UTC, sungeunbae approved these changes

2023-04-18 22:53 UTC, merged