correctly utilise simulation root argument to create3d
ucgmsim/slurm_gm_workflow pull request #520
Opened 2024-06-26 21:31 UTC by lispandfound

Fixes #518

2024-06-27 01:05 UTC, AndrewRidden-Harper approved these changes

2024-06-27 01:14 UTC, sungeunbae requested changes
I understand create_e3d.py is always used by importing it instead of running it as a script, so this change and introducing SIM_ROOT parameter doesn't cause any degradation.

Can you remove sys.path.append() line (line 28)? Then could os.path could be removed.

2024-06-27 02:38 UTC, lispandfound commented
> I understand create_e3d.py is always used by importing it instead of running it as a script, so this change and introducing SIM_ROOT parameter doesn't cause any degradation.
> 
> Can you remove sys.path.append() line (line 28)? Then could os.path could be removed.

Done. Also removed a `from __future__ import print_function` that was not required anymore.

2024-06-30 20:46 UTC, claudio525 approved these changes

2024-06-30 23:28 UTC, joelridden approved these changes

2024-06-30 23:54 UTC, sungeunbae approved these changes

2024-07-01 02:19 UTC, merged